/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Donations {
	unfiltered: Donation[];
	rejected: Donation[];
	pending: Donation[];
	approved: Donation[];
}
export interface Donation {
	displayName: string;
	message: string;
	participantID: number;
	amount: string;
	donorID: string;
	avatarImageURL: string;
	createdDateUTC: string;
	teamID?: number;
}
